<a href="https://colab.research.google.com/github/wongjulianne/ds_projects/blob/main/NYC_Rolling_Sales_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [18]:
files = ['rollingsales_bronx.xlsx',
         'rollingsales_brooklyn.xlsx',
         'rollingsales_manhattan.xlsx',
         'rollingsales_queens.xlsx',
         'rollingsales_statenisland.xlsx']

In [19]:
df1 = pd.DataFrame()

for file in files:
    df_file = pd.read_excel(file, skiprows=4)
    df1 = df1.append(df_file, ignore_index=True)

<ipython-input-19-b3f6e37fa8f9>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df_file, ignore_index=True)
<ipython-input-19-b3f6e37fa8f9>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df_file, ignore_index=True)
<ipython-input-19-b3f6e37fa8f9>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df_file, ignore_index=True)
<ipython-input-19-b3f6e37fa8f9>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df_file, ignore_index=True)
<ipython-input-19-b3f6e37fa8f9>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df_file, ignore_index=True)

In [20]:
df1.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3028,24,NaN,A1,410 EAST 179TH STREET,NaN,...,1.0,0.0,1.0,1842.0,2048.0,1901.0,1,A1,655000,2022-11-01
1,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,65,NaN,A1,4455 PARK AVENUE,NaN,...,1.0,0.0,1.0,1622.0,1587.0,1899.0,1,A1,520000,2022-10-26
2,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,66,NaN,A1,4453 PARK AVENUE,NaN,...,1.0,0.0,1.0,1646.0,1497.0,1899.0,1,A1,215000,2023-04-18
3,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,66,NaN,A1,4453 PARK AVENUE,NaN,...,1.0,0.0,1.0,1646.0,1497.0,1899.0,1,A1,570000,2023-08-23
4,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3035,52,NaN,A1,461 EAST 178 STREET,NaN,...,1.0,0.0,1.0,1782.0,1548.0,1899.0,1,A1,0,2023-04-14

In [21]:
df1['BOROUGH'].unique()

array([2, 3, 1, 4, 5])

In [22]:
b_map = {2: 'Bronx', 3: 'Brooklyn', 1:'Manhattan', 4:'Queens', 5:'Staten Island'}

In [25]:
df1=df1.replace({'BOROUGH':b_map})
df1

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,1,3028,24,NaN,A1,410 EAST 179TH STREET,NaN,...,1.0,0.0,1.0,1842.0,2048.0,1901.0,1,A1,655000,2022-11-01
1,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,65,NaN,A1,4455 PARK AVENUE,NaN,...,1.0,0.0,1.0,1622.0,1587.0,1899.0,1,A1,520000,2022-10-26
2,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,66,NaN,A1,4453 PARK AVENUE,NaN,...,1.0,0.0,1.0,1646.0,1497.0,1899.0,1,A1,215000,2023-04-18
3,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,66,NaN,A1,4453 PARK AVENUE,NaN,...,1.0,0.0,1.0,1646.0,1497.0,1899.0,1,A1,570000,2023-08-23
4,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,1,3035,52,NaN,A1,461 EAST 178 STREET,NaN,...,1.0,0.0,1.0,1782.0,1548.0,1899.0,1,A1,0,2023-04-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73157,Staten Island,WOODROW,05 TAX CLASS 1 VACANT LAND,1,6970,84,NaN,A1,N/A LENEVAR AVENUE,NaN,...,1.0,0.0,1.0,2603.0,0.0,2022.0,1,V0,1116638,2022-12-19
73158,Staten Island,WOODROW,05 TAX CLASS 1 VACANT LAND,1,6970,85,NaN,A1,N/A LENEVAR AVENUE,NaN,...,1.0,0.0,1.0,2551.0,0.0,NaN,1,V0,1116638,2022-12-19
73159,Staten Island,WOODROW,05 TAX CLASS 1 VACANT LAND,1B,6970,86,NaN,V0,N/A LENEVAR AVENUE,NaN,...,0.0,0.0,0.0,2597.0,0.0,2023.0,1,V0,1116638,2022-12-19
73160,Staten Island,WOODROW,05 TAX CLASS 1 VACANT LAND,1B,6970,87,NaN,V0,96 LENEVAR AVENUE,NaN,...,0.0,0.0,0.0,2644.0,0.0,2023.0,1,V0,1116638,2022-12-19
73161,Staten Island,WOODROW,22 STORE BUILDINGS,4,7144,510,NaN,K2,3120 ARTHUR KILL ROAD,NaN,...,0.0,1.0,1.0,98116.0,7795.0,1977.0,4,K2,5600000,2022-12-19

In [26]:
df1.describe()

,BLOCK,LOT,EASEMENT,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,SALE PRICE
count,73162.000000,73162.000000,0.0,73156.000000,55398.000000,42163.000000,57713.000000,3.984800e+04,3.984800e+04,68299.000000,73162.000000,7.316200e+04
mean,4166.823119,388.785695,NaN,10846.743589,3.527727,0.403577,3.681060,7.588851e+03,6.723144e+03,1952.784228,1.657609,1.338843e+06
std,3544.044089,655.806349,NaN,567.508343,24.804713,8.223940,25.365637,1.398126e+05,4.867396e+04,36.525356,0.794325,8.084588e+06
min,1.000000,1.000000,NaN,10001.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,220.000000,1.000000,0.000000e+00
25%,1263.000000,22.000000,NaN,10304.000000,1.000000,0.000000,1.000000,2.000000e+03,1.386000e+03,1925.000000,1.000000,0.000000e+00
50%,3239.000000,51.000000,NaN,11209.000000,1.000000,0.000000,1.000000,2.500000e+03,1.990000e+03,1950.000000,2.000000,5.160000e+05
75%,6186.000000,1003.000000,NaN,11356.000000,2.000000,0.000000,2.000000,4.000000e+03,2.848000e+03,1975.000000,2.000000,9.990000e+05
max,16350.000000,9079.000000,NaN,11697.000000,1272.000000,1178.000000,1272.000000,9.166500e+06,2.400000e+06,2023.000000,4.000000,5.981558e+08

In [27]:
df1.dtypes

BOROUGH                                   object
NEIGHBORHOOD                              object
BUILDING CLASS CATEGORY                   object
TAX CLASS AT PRESENT                      object
BLOCK                                      int64
LOT                                        int64
EASEMENT                                 float64
BUILDING CLASS AT PRESENT                 object
ADDRESS                                   object
APARTMENT NUMBER                          object
ZIP CODE                                 float64
RESIDENTIAL UNITS                        float64
COMMERCIAL UNITS                         float64
TOTAL UNITS                              float64
LAND SQUARE FEET                         float64
GROSS SQUARE FEET                        float64
YEAR BUILT                               float64
TAX CLASS AT TIME OF SALE                  int64
BUILDING CLASS AT TIME OF SALE            object
SALE PRICE                                 int64
SALE DATE                         datetime64[ns]
dtype: object

In [28]:
df1.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASEMENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE',
       'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE PRICE', 'SALE DATE'],
      dtype='object')

In [29]:
df = df1[['BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY', 'BLOCK', 'LOT',
      'ADDRESS', 'ZIP CODE','LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'SALE PRICE', 'SALE DATE']]

In [30]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,BLOCK,LOT,ADDRESS,ZIP CODE,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,SALE PRICE,SALE DATE
0,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,3028,24,410 EAST 179TH STREET,10457.0,1842.0,2048.0,1901.0,655000,2022-11-01
1,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,3030,65,4455 PARK AVENUE,10457.0,1622.0,1587.0,1899.0,520000,2022-10-26
2,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,3030,66,4453 PARK AVENUE,10457.0,1646.0,1497.0,1899.0,215000,2023-04-18
3,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,3030,66,4453 PARK AVENUE,10457.0,1646.0,1497.0,1899.0,570000,2023-08-23
4,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,3035,52,461 EAST 178 STREET,10457.0,1782.0,1548.0,1899.0,0,2023-04-14

In [31]:
df.dtypes

BOROUGH                            object
NEIGHBORHOOD                       object
BUILDING CLASS CATEGORY            object
BLOCK                               int64
LOT                                 int64
ADDRESS                            object
ZIP CODE                          float64
LAND SQUARE FEET                  float64
GROSS SQUARE FEET                 float64
YEAR BUILT                        float64
SALE PRICE                          int64
SALE DATE                  datetime64[ns]
dtype: object

In [32]:
df.isna().sum()

BOROUGH                        0
NEIGHBORHOOD                   0
BUILDING CLASS CATEGORY        0
BLOCK                          0
LOT                            0
ADDRESS                        0
ZIP CODE                       6
LAND SQUARE FEET           33314
GROSS SQUARE FEET          33314
YEAR BUILT                  4863
SALE PRICE                     0
SALE DATE                      0
dtype: int64

In [33]:
df[df['ZIP CODE'].isnull()]

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,BLOCK,LOT,ADDRESS,ZIP CODE,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,SALE PRICE,SALE DATE
15856,Brooklyn,EAST NEW YORK,29 COMMERCIAL GARAGES,4494,1,N/A LINDEN BOULEVARD,NaN,95000.0,0.0,NaN,35206224,2023-07-17
24346,Brooklyn,SPRING CREEK,05 TAX CLASS 1 VACANT LAND,4585,165,N/A VANDALIA AVENUE,NaN,81867.0,0.0,NaN,163500,2022-10-06
24347,Brooklyn,SPRING CREEK,05 TAX CLASS 1 VACANT LAND,4585,167,N/A VANDALIA AVENUE,NaN,6440.0,0.0,NaN,163500,2022-10-06
24348,Brooklyn,SPRING CREEK,05 TAX CLASS 1 VACANT LAND,4585,225,N/A DREW STREET,NaN,2582.0,0.0,NaN,163500,2022-10-06
43620,Queens,ARVERNE,29 COMMERCIAL GARAGES,16013,1,N/A BEACH CHANNEL DRIVE,NaN,32939.0,0.0,NaN,5600000,2023-02-02
70724,Staten Island,OAKWOOD-BEACH,05 TAX CLASS 1 VACANT LAND,4785,1,N/A PROMENADE AVENUE,NaN,28980.0,0.0,NaN,0,2022-11-10

In [34]:
df['ZIP CODE'] = df['ZIP CODE'].fillna(method='ffill')

<ipython-input-34-6e996118f863>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ZIP CODE'] = df['ZIP CODE'].fillna(method='ffill')

In [35]:
df['ZIP CODE'] = df['ZIP CODE'].astype('int')

<ipython-input-35-4985857204cd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ZIP CODE'] = df['ZIP CODE'].astype('int')

In [36]:
df = df[df['SALE PRICE'] != 0]

In [37]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,BLOCK,LOT,ADDRESS,ZIP CODE,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,SALE PRICE,SALE DATE
0,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,3028,24,410 EAST 179TH STREET,10457,1842.0,2048.0,1901.0,655000,2022-11-01
1,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,3030,65,4455 PARK AVENUE,10457,1622.0,1587.0,1899.0,520000,2022-10-26
2,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,3030,66,4453 PARK AVENUE,10457,1646.0,1497.0,1899.0,215000,2023-04-18
3,Bronx,BATHGATE,01 ONE FAMILY DWELLINGS,3030,66,4453 PARK AVENUE,10457,1646.0,1497.0,1899.0,570000,2023-08-23
5,Bronx,BATHGATE,02 TWO FAMILY DWELLINGS,2904,22,454 EAST 172 STREET,10457,1658.0,1428.0,1901.0,350000,2023-06-26

In [38]:
df.to_csv('nyc_rolling_sales.csv', index=False)